import React, { useState } from 'react';
import { Form, Button, Container, Alert } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import { UserRole } from '../types';
import * as api from '../services/api';
// Import useTranslation

const RegisterPage = () => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [role, setRole] = useState(UserRole.BUYER);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    if (password !== confirmPassword) {
      setError('Passwords do not match'); // Translated error
      setLoading(false);
      return;
    }
    setError('');
    setSuccess('');

    try {
      const registrationData = { name, email, password, role };
      // registrationData.registrationNumber is now automatically generated by the backend for buyers
      const response = await api.register(registrationData);
      
      if (response.data.isPending) {
        // Sellers and riders need approval
        setSuccess('Registration successful! Your account is pending admin approval. You will be notified once approved.');
      } else {
        // Buyers are auto-approved
        setSuccess('✅ Registration successful! You can now login and start shopping.');
      }
      
      setTimeout(() => {
        navigate('/login');
      }, 3000);
    } catch (err: any) {
      console.error("Registration failed:", err);
      setError(err.response?.data?.message || 'Registration failed'); // Translated error
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container className="d-flex flex-column align-items-center justify-content-center min-vh-100 p-3">
      <div className="w-100" style={{ maxWidth: '500px' }}>
        <h2 className="text-center mb-4">Register</h2>
        {error && <Alert variant="danger">{error}</Alert>}
        {success && <Alert variant="success">{success}</Alert>}
        {(role === UserRole.SELLER || role === UserRole.RIDER) && (
          <Alert variant="info">
            <strong>ℹ️ Admin Approval Required:</strong> {role === UserRole.SELLER ? 'Seller' : 'Rider'} accounts must be approved by an administrator before you can access the portal.
          </Alert>
        )}
        {role === UserRole.BUYER && (
          <Alert variant="success">
            <strong>✅ Instant Access:</strong> Buyer accounts are automatically approved. You can login immediately after registration!
          </Alert>
        )}
        <Form onSubmit={handleSubmit} className="p-4 border rounded shadow-sm bg-white">
          <Form.Group className="mb-3" controlId="formBasicName">
            <Form.Label>Name</Form.Label>
            <Form.Control
              type="text"
              placeholder="Enter name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formBasicEmail">
            <Form.Label>Email Address</Form.Label>
            <Form.Control
              type="email"
              placeholder="Enter email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formBasicPassword">
            <Form.Label>Password</Form.Label>
            <Form.Control
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formBasicConfirmPassword">
            <Form.Label>Confirm Password</Form.Label>
            <Form.Control
              type="password"
              placeholder="Confirm password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3">
            <Form.Label>Register As</Form.Label>
            <Form.Control as="select" value={role} onChange={(e) => setRole(e.target.value as UserRole)}>
              <option value={UserRole.BUYER}>Buyer</option>
              <option value={UserRole.SELLER}>Seller</option>
              <option value={UserRole.RIDER}>Rider</option>
            </Form.Control>
          </Form.Group>

          <Button variant="primary" type="submit" className="w-100" disabled={loading}>
            {loading ? 'Registering...' : 'Register'}
          </Button>
        </Form>
      </div>
    </Container>
  );
};

export default RegisterPage;
