import React, { useState } from 'react';
import { Form, Button, Container, Alert } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import { UserRole } from '../types';
import * as api from '../services/api';
import { useTranslation } from 'react-i18next'; // Import useTranslation

const RegisterPage = () => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [role, setRole] = useState(UserRole.Buyer);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { t } = useTranslation(); // Initialize useTranslation

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    if (password !== confirmPassword) {
      setError(t('passwords_do_not_match_error')); // Translated error
      setLoading(false);
      return;
    }
    setError('');
    setSuccess('');

    try {
      const registrationData = { name, email, password, role };
      // registrationData.registrationNumber is now automatically generated by the backend for buyers
      await api.register(registrationData);
      setSuccess(t('registration_successful_message')); // Translated success
      setTimeout(() => {
        navigate('/login');
      }, 2000);
    } catch (err: any) {
      console.error("Registration failed:", err);
      setError(err.response?.data?.message || t('registration_failed_error')); // Translated error
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container className="d-flex flex-column align-items-center justify-content-center min-vh-100 p-3">
      <div className="w-100" style={{ maxWidth: '500px' }}>
        <h2 className="text-center mb-4">{t('register_title')}</h2>
        {error && <Alert variant="danger">{error}</Alert>}
        {success && <Alert variant="success">{success}</Alert>}
        <Form onSubmit={handleSubmit} className="p-4 border rounded shadow-sm bg-white">
          <Form.Group className="mb-3" controlId="formBasicName">
            <Form.Label>{t('name_label')}</Form.Label>
            <Form.Control
              type="text"
              placeholder={t('enter_name_placeholder')}
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formBasicEmail">
            <Form.Label>{t('email_address_label')}</Form.Label>
            <Form.Control
              type="email"
              placeholder={t('enter_email_placeholder')}
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formBasicPassword">
            <Form.Label>{t('password_label')}</Form.Label>
            <Form.Control
              type="password"
              placeholder={t('password_placeholder')}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3" controlId="formBasicConfirmPassword">
            <Form.Label>{t('confirm_password_label')}</Form.Label>
            <Form.Control
              type="password"
              placeholder={t('confirm_password_placeholder')}
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              required
            />
          </Form.Group>

          <Form.Group className="mb-3">
            <Form.Label>{t('register_as_label')}</Form.Label>
            <Form.Control as="select" value={role} onChange={(e) => setRole(e.target.value as UserRole)}>
              <option value={UserRole.Buyer}>{t('buyer_role')}</option>
              <option value={UserRole.Seller}>{t('seller_role')}</option>
              <option value={UserRole.Driver}>{t('driver_role')}</option>
            </Form.Control>
          </Form.Group>

          <Button variant="primary" type="submit" className="w-100" disabled={loading}>
            {loading ? t('registering_button') : t('register_button')}
          </Button>
        </Form>
      </div>
    </Container>
  );
};

export default RegisterPage;
